### PR TITLE
Add custom loaders structure

### PR DESCRIPTION
**Pull request by progre**
ref: #294

Usage:

1. Create your own loader ([example](https://github.com/progre/hitorilive/blob/d0aee1597f85d95757aa8efb75399e1945a4151b/src/public/js/infrastructures/ObservableLoader.ts))

2. Create player;
```
flvJS.createPlayer(
  {
    type: 'flv',
    isLive: true,
  },
  {
    loader: new ObservableLoader(source),
  },
);
```

### CODE REVIEW

**Comment by xqq** [comment]
Very glad to receive this pull request from you.

The custom loader should be passed with a class (*aka. Constructor*), because in VOD mode:
- IOController will re-create a new loader to recover loading if detected a network Early-EOF
- IOController will re-create a new loader when need to resume loading from a paused state
- For multipart playback, IOController will create a new loader for every MediaSegment

Rename the field name in Config `loader` to be `customLoader` will be better.

**Comment by progre** [comment]
OK. I'm replace a instance of custom loader with a constructor.

So, it's usage was changed like this;

```
flvJS.createPlayer(
  {
    type: 'flv',
    isLive: true,
  },
  {
    customLoader: ObservableLoader,
    customLoaderParameters: myCustomParams,
  },
);
```

**Comment by xqq** [comment]
If extra parameters are needed for custom loader's constructor, I think using closure to wrap the constructor may solve it.

But why `customLoaderParameters` is not yet used?

**Comment by progre** [comment]
hmm... I don't know how to wrap constructor using closure.
Can you tell me how to do it?

**Comment by xqq** [comment]
```js
function init() {
    let extraParam = null;

    function createObservableLoader(seekHandler, config) {
        return new ObservableLoader(extraParam, seekHandler, config);
    }
    
    flvjs.createPlayer({
        type: 'flv',
        isLive: true
    }, {
        customLoader: createObservableLoader
    });
}
```

このようにできるかも

**Comment by progre** [comment]
I see. Certainly, It seems to be possible.
I removed the parameter in type definition.

**Comment by xqq** [comment]
https://github.com/Bilibili/flv.js/pull/307/files#diff-e7b9ff559443937e9bb0f0932a5d11dbR232
How do you think about it?

**Comment by progre** [comment]
`Range` can be used to extend `BaseLoader#open`;

```
import flvJS, { MediaSegment, Range } from 'flv.js';
...
class MyCustomLoader extends flvJS.BaseLoader {
  open(dataSource: MediaSegment, range: Range) {
...
```

(but I don't use `range` parameter yet. So I don't need it.)

**Comment by xqq** [comment]
I think it is accessible through the namespace FlvJs... aka `FlvJs.MediaSegment / FlvJs.Range`.
I'm not familiar with TypeScript so probably wrong.

**Comment by progre** [comment]
hmm.. It can this way;
```
export declare namespace FlvJs {
...
```

but, This is need import like this. I think this is a little ugly.
```
import flvJS, { FlvJs } from 'flv.js';
```

**Comment by xqq** [comment]
Merged, thanks!

I will manually remove the exported type until found other solutions to refactor the d.ts.

**Comment by xqq** [comment]
#310

**Comment by melodysummer** [comment]
@progre flv支持cumtomloader吗 你是自己改的源码吗

**Comment by melodysummer** [comment]
@xqq flv支持cumtomloader吗 我看config里没有这个参数
是需要改源码吗

**Comment by xqq** [comment]
WHY USE CHINESE IN SUCH A PURE ENGLISH PULL REQUEST?

**Comment by melodysummer** [comment]
a new learner... ok, I'll explain it in English.
flv.js supports the customloader config?  @xqq

**Pull request merged**
