### PR TITLE
feat: skip tag which has error timestamp

### PR DESCRIPTION
**Pull request by Dcatfly**
The current timestamp is smaller than last timestamp, which will cause current dts to be smaller than last dts. This will cause the browser to get stuck when playing the video. This may be a problem with the push order of the server, but adding processing measures in flv.js can better avoid this problem.

### CODE REVIEW

**Comment by Dcatfly** [comment]
#624

**Comment by xqq** [comment]
Merged, thanks

**Comment by xqq** [comment]
AFAIK timestamp of tags in the FLV tag sequence doesn't really need to keep monotonic increasing.

Only timestamps of tags that belong to a certain stream should keep monotonic increasing in the sequence of the stream.

In other words, a new video tag's timestamp should be equal to or greater than the previous video tag's timestamp.
Similarly, a new audio tag's timestamp should be equal to or greater than the previous audio tag's timestamp.

**Comment by xqq** [comment]
Will revert.

**Comment by Dcatfly** [comment]
> AFAIK timestamp of tags in the FLV tag sequence doesn't really need to keep monotonic increasing.
> 
> Only timestamps of tags that belong to a certain stream should keep monotonic increasing in the sequence of the stream.
> 
> In other words, a new video tag's timestamp should be equal to or greater than the previous video tag's timestamp.
> Similarly, a new audio tag's timestamp should be equal to or greater than the previous audio tag's timestamp.

Thanks Reply. 
But I don't understand the meaning of "_Only timestamps of tags that belong to a certain stream should keep monotonic increasing in the sequence of the stream_." too much. In what scenarios is it okay for the timestamps to be out of order? This seems to be the opposite of "_In other words, a new video tag's timestamp should be equal to or greater than the previous video tag's timestamp._". 
Looking forward for your reply, thank you.

**Comment by xqq** [comment]
Some encoder/publisher writes malformed timestamps at times. But if any video tag's timestamp is equaled to or greater than the previous video tag, and similarly any audio tag's timestamp is equaled to or greater than the previous audio tag, it wouldn't cause playback issues.

Sometimes the `onMetaData` script tag will be received again which may have a timestamp of 0.

So you have to compare the tag timestamp with the previous tag which has the same type,
(for video tag, compare with previous video tag), and ignore timestamp checking for script tags.

**Comment by Dcatfly** [comment]
> Some encoder/publisher writes malformed timestamps at times. But if any video tag's timestamp is equaled to or greater than the previous video tag, and similarly any audio tag's timestamp is equaled to or greater than the previous audio tag, it wouldn't cause playback issues.
> 
> Sometimes the `onMetaData` script tag will be received again which may have a timestamp of 0.
> 
> So you have to compare the tag timestamp with the previous tag which has the same type,
> (for video tag, compare with previous video tag), and ignore timestamp checking for script tags.

I understand what you mean, I will submit a new PR when I have time. Thanks.

**Comment by xqq** [comment]
@Dcatfly 
09982ef

**Pull request merged**
