### PR TITLE
Wanted to give you a logo and some object literal shorthand goodness

### PR DESCRIPTION
**Pull request by qbunt**
LOVE this project. Wanted to help out and give you a logo and help out any way I could. I didn't touch core code much, but reading through the top level, saw this minor update I could make and made it. Let me know if you'd like any changes. Cheers and keep it up!

### CODE REVIEW

**Comment by qbunt** [comment]
Also, linted my changes and looks like everything passed OK, wanted to make sure I followed your conventions.

**Comment by xqq** [comment]
Thank you but the logo is not suitable enough. Logo is unnecessary for a player library.

In src/flv.js, code in master branch is expressing much more clearly than your patch.

**Comment by ChiChou** [comment]
So anybody can make up a logo with in 30s and leave his name in the contributors
flv js

**Comment by qbunt** [comment]
Definitely didn't put my name anywhere, didn't mean to offend, and spent more than 30 seconds. Not sure what's bothering you so much about this.

**Pull request closed without merging**
