### PR TITLE
FetchStreamLoader: Fix memory leak

### PR DESCRIPTION
**Pull request by spacemeowx2**

### CODE REVIEW

**Comment by xqq** [comment]
Merged, thanks

**Comment by xqq** [comment]
https://github.com/Bilibili/flv.js/releases/tag/v1.3.3
Fix #58 #123 #180 #188 

修复 FetchStreamLoader 长时间直播流的内存泄露问题.

**Comment by AngryPowman** [comment]
It's very helpful to me

**Comment by CoderNeko** [comment]
It's very helpful to me

**Comment by sky0014** [comment]
Nice work 👍

**Pull request merged**
