### PR TITLE
Added missing documentation

### PR DESCRIPTION
**Pull request by rafa8626**
Fix for #163

### CODE REVIEW

**Comment by rafa8626** [comment]
@xqq Any chances this might get merged?

**Comment by xqq** [comment]
I'm sorry that I have missed the notification of this pull request.
Thanks for your work! There's still some mistakes so I will merge it and fix them.

**Comment by rafa8626** [comment]
Thanks

**Comment by rafa8626** [comment]
Thanks

**Comment by xqq** [comment]
Refined https://github.com/Bilibili/flv.js/commit/f0b3fec859a18c03f08e7888940c2b331fb67ffa

**Pull request merged**
