### PR TITLE
use a new silent frame insert algorithm for audio remux

### PR DESCRIPTION
**Pull request by jamken**
the old algorithm cannot cover some common situation, like:
1. audio frame dts does not increase by a standard duration, sometimes it increase for a large duration(more than 1.5 * refSampleDuration), sometimes it increase for a small duration. But the average duration is more or less to refSampleDuration. the old algorithm would insert silent frames which result into video/audio unsync.
2. for network living stream, because of network jitter or frame lost, the encoder would generate the audio frames whose dts is not correct. but if the gap between two adjacent frame is not over 1.5 * refSampleDuration and the accumulate gap would become larger and larger. the old algorithm never insert silent frames for this case.

### CODE REVIEW

**Comment by saysmy** [comment]
已测试我们平台不同时长的数十个直播流，均正常！没有音画不同步现象，推荐！

**Comment by x-ray-s** [comment]
Please keep up with code style, and remove invalid code modify.

**Comment by lynxerzhang** [comment]
awesome, but after merge “flv.js master“, there was a conflict (mp4-remuxer.js), could you merge it

**Comment by xqq** [comment]
Merged, thanks!

**Pull request merged**
